import type { Metadata } from "next";
import { Courier_Prime, Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import React from "react";
import Header from "@/components/molecules/Header";
import Footer from "@/components/molecules/Footer";

const courierPrime = Courier_Prime({
  variable: "--font-courier-prime",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "AtlanticJ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Providers>
      <body className={`${courierPrime.variable} ${courierPrime.className} antialiased`}>
          <Header logo="/logo.svg" alt="Logo" width={100} height={100} />
          <main className=" flex min-h-screen w-full max-w-3xl flex-col items-center justify-between py-32 px-16 light:bg-background dark:bg-black sm:items-start">
            {children}
          </main>
        <Footer />
      </body>
      </Providers>
    </html>
  );
}
